version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./portfolio_analytics/common/data:/app/portfolio_analytics/common/data
    # Runs container processes with host user's UID/GID to avoid permission issues
    # Files created in volumes will be owned by the host user instead of root
    user: "${UID:-1000}:${GID:-1000}"

  dashboard:
    build:
      context: .
      dockerfile: dashboard.Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./portfolio_analytics/common/data:/app/portfolio_analytics/common/data
    # Runs container processes with host user's UID/GID to avoid permission issues
    # Files created in volumes will be owned by the host user instead of root
    user: "${UID:-1000}:${GID:-1000}"
