volumes:
  shared-data:

services:
  data:
    image: ghcr.io/gbourniq/portfolio_analytics/data:${GIT_TAG:-latest}
    build:
      context: .
      dockerfile: data.Dockerfile
    volumes:
      - shared-data:/data
    user: "appuser:appuser"

  api:
    image: ghcr.io/gbourniq/portfolio_analytics/api:${GIT_TAG:-latest}
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - shared-data:/app/data
    user: "appuser:appuser"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 384M
        reservations:
          memory: 192M

  dashboard:
    image: ghcr.io/gbourniq/portfolio_analytics/dashboard:${GIT_TAG:-latest}
    build:
      context: .
      dockerfile: dashboard.Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - shared-data:/app/data
    user: "appuser:appuser"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M
        reservations:
          memory: 512M
