services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./portfolio_analytics/common/data:/app/portfolio_analytics/common/data
    # Runs container processes with host user's UID/GID to avoid permission issues
    # Files created in volumes will be owned by the host user instead of root
    user: "${UID:-1000}:${GID:-1000}"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          memory: 128M

  dashboard:
    build:
      context: .
      dockerfile: dashboard.Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./portfolio_analytics/common/data:/app/portfolio_analytics/common/data
    # Runs container processes with host user's UID/GID to avoid permission issues
    # Files created in volumes will be owned by the host user instead of root
    user: "${UID:-1000}:${GID:-1000}"
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 512M
        reservations:
          memory: 256M
